# config.yaml
paths:
  roster_xlsx: "./quotazioni/Quotazioni_Fantacalcio_Stagione_2025_26.xlsx"
  history_xlsx: 
    - "./statistiche/Statistiche_Fantacalcio_Stagione_2024_25.xlsx" 
    - "./statistiche/Statistiche_Fantacalcio_Stagione_2023_24.xlsx" 
    - "./statistiche/Statistiche_Fantacalcio_Stagione_2022_23.xlsx" 
  pdf_rigoristi: "./extra/rigoristi.pdf"
  pdf_punizioni: "./extra/punizioni.pdf"
  pdf_formazioni: "./extra/formazionitipo.pdf"
  pdf_afcon: "./extra/coppadafrica.pdf"
  aliases_yaml: null   # optional: "/path/aliases.yaml"

params:
  recency_weights: [0.6, 0.3, 0.1]     # most recent → oldest
  start_probs: {starter: 0.85, battle: 0.65, battle3: 0.55, backup: 0.35}
  four_back_freq: 0.85
  afcon_default_miss: 3
  pk_shares: [0.7, 0.2, 0.1]
  pk_conv_default: 0.80
  sp_shares: {primary: 0.55, secondary: 0.30, tertiary: 0.15}
  sp_assist_fraction: 0.33           # fraction of team assists from set pieces (simple proxy)
  modifier_bands:                     # μ_team (avg Mv of GK+3 DEF) → EV per week
    - {max: 6.25, ev: 0.5}
    - {max: 6.50, ev: 1.0}
    - {max: 6.75, ev: 1.5}
    - {max: 7.00, ev: 2.0}
    - {max: 7.25, ev: 2.8}
    - {max: 7.50, ev: 3.7}
    - {max: 10.0, ev: 4.5}
  replacement_cut:
    P: 10
    D: 43       # 40–45 window; pick a single value
    C: 38
    A: 28
  pricing:
    blend_fvm_weight: 0.30
    room_bias: {P: 1.15, D: 1.00, C: 0.90, A: 1.12}
    star_exponent: 1.05

output:
  projections_csv: "./outputs/projections.csv"
  prices_csv: "./outputs/stop_prices.csv"
